### ISSUE TITLE
Bug: calculating secondsSinceLast in HeartbeatDispatcher.CheckDispatch

### ISSUE THREAD

**Issue by PeterDM65** [Furtif/POGOLib#10]
May I suggest following change in the function HeartbeatDispatcher.CheckDispatch(...) (line 43)
**New:**
var secondsSinceLast = DateTime.UtcNow.Subtract(_session.RpcClient.LastRpcMapObjectsRequest).**TotalSeconds**;
**Old:**
var secondsSinceLast = DateTime.UtcNow.Subtract(_session.RpcClient.LastRpcMapObjectsRequest).**Seconds**;

**Problem**:
When the difference in time is eg. 65 seconds then the result of **Seconds = 5** and for **TotalSeconds = 65**

**Comment by Furtif** [comment]
i go to try this

**Comment by Furtif** [comment]
is only for select log type this var 

if (secondsSinceLast >= maxSeconds)
                        {
                            _session.Logger.Debug($"Refreshing MapObjects, reason: 'secondsSinceLast({secondsSinceLast}) >= maxSeconds({maxSeconds})'.");
                            canRefresh = true;
                        }
                        else if (metersMoved >= minDistance)
                        {
                            _session.Logger.Debug($"Refreshing MapObjects, reason: 'metersMoved({metersMoved}) >= minDistance({minDistance})'.");
                            canRefresh = true;
                        }


totalseconds show allways  _session.Logger.Debug($"Refreshing MapObjects, reason: 'metersMoved({metersMoved}) >= minDistance({minDistance})'.");

**Comment by PeterDM65** [comment]
At this moment the result may seem correct, but it all depends on the values of minSeconds, maxSeconds and minDistance (respectivily GetMapObjectsMinRefreshSeconds, GetMapObjectsMaxRefreshSeconds, GetMapObjectsMinDistanceMeters) when these values changes to eg. minValue = 60, maxValue=90 and minDistance = 1000 or you stays stationary (maybe these values will never change but you don't know), then the result will not be correct anymore ...

When minValue > 60 then you don't pass the test 'else if secondsSinceLast >= minSeconds)' and 'canRefresh' get never true

And wathever the reason is, in this case the value of secondsSinceLast is not calculated the correct way.

**Comment by Furtif** [comment]
Xd one log or other set canRefresh = true only log debug changes ...  values is only used to change debug comment

**Comment by Furtif** [comment]
Set to total ou leave seconds is same log and result, app set Player pos is always because xx meters

**Comment by PeterDM65** [comment]
in line 69 you test 'if (canRefresh)' and if true you do 'await Dispatch()' at line 73 so if canRefresh in not set to true you don't call the function 'Dispatch' and I suppose that this function is important !

**Comment by Furtif** [comment]
yes but  var secondsSinceLast = DateTime.UtcNow.Subtract(_session.RpcClient.LastRpcMapObjectsRequest).TotalSeconds; or seconds is same cantrefresh = true

**Comment by Furtif** [comment]
changed https://github.com/Furtif/POGOLib/commit/0c02e51c0701fdd62627a373f2a924e1b38b6c63

**Comment by PeterDM65** [comment]
Seconds is a value between -59 and 59 and TotalSeconds is not ... see MSDN
