### ISSUE TITLE
Bug: PokeHashHasher.PerformRequest - Handling of exceptions is faulty

### ISSUE THREAD

**Issue by PeterDM65** [Furtif/POGOLib#11]
**Situation**:
In line 161 you take a semaphore so only one Request at a time should be handled
In line 165->253 you have a loop for eventually handling retries
In line 167->252 you have a try catch finally block for catching exceptions but this block is inside the loop!!!
In line 169->241 you do the request and at the end you return the response (leaving the loop) and execute the finally block releasing the semaphore for the next request.

---> so far everything is oké

but when an exception occurs in line 169-241 the catch finally block will be executed and the program will delay for 1 second and afterwards the semaphore will be released in the finally block.
Since you are still in the loop the request will be retried ... and so on.

But since the semaphore is released an second request, when available, will be started!!! the moment you release the semaphore ...

**Comment by Furtif** [comment]
@PeterDM65 before 10 accounts buggued 100% XD now runs 80 but revise this if you whant. thanks

**Comment by Furtif** [comment]
https://github.com/Furtif/POGOLib/commit/558584367af9c5ff8ea74eb572ff363244d09563

**Comment by PeterDM65** [comment]
@Furtif how do i do that ? I am not that familiar with github.

**Comment by Furtif** [comment]
@PeterDM65 no worries look https://github.com/Furtif/POGOLib/commit/8e35bb389b2cabd2044117f09e2a6e2477495b79 see ok

**Comment by Furtif** [comment]
ops missed break; added now maybe continue for new retry...

**Comment by Furtif** [comment]
maybe 
// Key selection
            _keySelection.WaitOne(); 

rigtht here into do { section...

**Comment by PeterDM65** [comment]
I need to ask but is this a joke ?
At least version 5585843 did the job (i think) although the code is a bit messy,
version 8e35bb3 doesn't.
Problem: When no exception is thrown, the function always leave with a (not valid) response and no retries. When an exception is thrown, a jump to the finally block occurs and the function leaves with an exception  (no retries !!!!)
This evening I will make some time to post a cleaner solution based on version 5585843.

**Comment by Furtif** [comment]
https://github.com/Furtif/POGOLib/blob/core/POGOLib.Core/Util/Hash/PokeHashHasher.cs#L155 works fine

**Comment by Furtif** [comment]
ok reversed https://github.com/Furtif/POGOLib/commit/c56a9691f6043d25bef2ff42aebd54e3b9fb4c6e

**Comment by PeterDM65** [comment]
I would do something like this :
Sorry for possible typos (i did this in notepad++)
```
 private async Task<HttpResponseMessage> PerformRequest(HttpContent requestContent)
        {
            //Retries
            int retries = 3;

            // Key selection
            _keySelection.WaitOne();
try{
            HttpResponseMessage response = null;
            PokeHashAuthKey authKey;
            do
            {
                try
                {
                    var availableKeys = _authKeys.Where(x => x.Requests < x.MaxRequestCount).ToArray();
                    if (availableKeys.Length > 0)
                    {
                        authKey = availableKeys.First();
                        authKey.Requests += 1;
                    }
                    else
                    {
                        authKey = _authKeys
                            .OrderBy(x => x.RatePeriodEnd)
                            .First();
                        // Rate limit is over, so reset requests.
                        authKey.Requests = 0;
                    }

                    // Add hashkey
                    requestContent.Headers.Add("X-AuthToken", authKey.AuthKey);

                    // Initialize HttpClient.
                    using (var _httpClient = new HttpClient
                    {
                        BaseAddress = GetHashUri(authKey.AuthKey)
                    })
                    {
                        _httpClient.DefaultRequestHeaders.Clear();
                        _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        _httpClient.DefaultRequestHeaders.UserAgent.TryParseAdd("POGOLib.Core (https://github.com/Furtif/POGOLib)");
                        response = await _httpClient.PostAsync(Configuration.HashEndpoint, requestContent);
                        _httpClient.Dispose();
                    };

                    // Parse headers
                    int maxRequestCount;
                    int rateRequestsRemaining;
                    int ratePeriodEndSeconds;

                    IEnumerable<string> maxRequestsValue;
                    IEnumerable<string> requestsRemainingValue;
                    IEnumerable<string> ratePeriodEndValue;
                    if (response.Headers.TryGetValues("X-MaxRequestCount", out maxRequestsValue) &&
                        response.Headers.TryGetValues("X-RateRequestsRemaining", out requestsRemainingValue) &&
                        response.Headers.TryGetValues("X-RatePeriodEnd", out ratePeriodEndValue))
                    {
                        if (!int.TryParse(maxRequestsValue.First(), out maxRequestCount) ||
                            !int.TryParse(requestsRemainingValue.First(), out rateRequestsRemaining) ||
                            !int.TryParse(ratePeriodEndValue.FirstOrDefault(), out ratePeriodEndSeconds))
                        {
//                            _keySelection.Release();
                            throw new PokeHashException("Failed parsing pokehash response header values.");
                        }
                    }
                    else
                    {
//                        _keySelection.Release();
                        throw new PokeHashException("Failed parsing pokehash response headers.");
                    }

                    // Use parsed headers
                    if (!authKey.IsInitialized)
                    {
                        authKey.MaxRequestCount = maxRequestCount;
                        authKey.Requests = authKey.MaxRequestCount - rateRequestsRemaining;
                        authKey.IsInitialized = true;
                    }

                    var ratePeriodEnd = TimeUtil.GetDateTimeFromSeconds(ratePeriodEndSeconds);
                    if (ratePeriodEnd > authKey.RatePeriodEnd)
                    {
                        authKey.RatePeriodEnd = ratePeriodEnd;
                    }

                    if (response == null)
                    {
//                        _keySelection.Release();
                        throw new PokeHashException("Missed hash response Data");
                    }
//                    _keySelection.Release();
                    return response;
                }
                catch
                {
//                    await Task.Delay(1000);
//                    continue;
                }
//                finally
//                {
	await Task.Delay(1000);
                    retries--;
//                    _keySelection.Release();
//                }
            } while (retries > 0);
}
finally
{
            _keySelection.Release();
}
            throw new PokeHashException("Hash API server might be down.");
        }
```

**Comment by Furtif** [comment]
pushed @PeterDM65 thanks 👍

**Comment by Xelwon** [comment]
Invalid solution.

finally block is not run if there is a return or throw in the try block.
only is run if the normal flow in try block or catch blocks are continued.

https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/try-finally

**Comment by Furtif** [comment]
humm yes 192 account 2 throw new PokeHashException("Hash API server might be down."); on into code at @Xelwon  into new review this get error 429 pokehash ++

**Comment by PeterDM65** [comment]
@Xelwon i don't understand spanish, but the english version i do.  This is what the english version states : 
"By using a finally block, you can clean up any resources that are allocated in a try block, and you can run code even if an exception occurs in the try block. Typically, the statements of a finally block run when control leaves a try statement. The transfer of control can occur as a result of normal execution, of execution of a break, continue, goto, or return statement, or of propagation of an exception out of the try statement."

So explain why my solution is invalid ...

Keep also in mind that in the do loop there is another try catch block that handles most of (all) possible exceptions. 
@Furtif  my solution is correct and will handle exceptions and returns as it should !!! Review/Test the code and you will see . Put a breakpoint at the return statement and a breakpoint in the finally block and run the program...

**Comment by Furtif** [comment]
Ok I think both are right, by experience and real test (several accounts) I got better results like this one today than I was before, or with I did at https://github.com/Furtif/POGOLib/commit/8e35bb389b2cabd2044117f09e2a6e2477495b79 now it's in this from semafore: s

**Comment by Xelwon** [comment]
:|, sorry, you are right. Your solution should be valid. The block "finally" is always executed.
