### ISSUE TITLE
google BadAuthentication

### ISSUE THREAD

**Issue by MortenMeisler** [Furtif/POGOLib#15]
Google returned an error message: 'BadAuthentication''

Can anyone give a step by step of how to log in with my google account. Tried replacing the environment variables with google email / password in the Demo.ConsoleApp project.

```
var usernameStr = Environment.GetEnvironmentVariable("myemail@gmail.com") ?? ""; // Your PTC username
            var passwordStr = Environment.GetEnvironmentVariable("mypassword") ?? ""; // Your PTC password
```

Thanks

**Comment by Furtif** [comment]
Hello pogolib is not good for moment, this uses hash services and all this need more infos..

**Comment by M3G4THEKING** [comment]
@MortenMeisler  The api from bossland is off, check https://discordapp.com/channels/208436903735853057/260772308086423552
