### ISSUE TITLE
SendRemoteProcedureCall - Possible problem with throttleDifference?

### ISSUE THREAD

**Issue by PeterDM65** [Furtif/POGOLib#2]
https://github.com/Furtif/POGOLib/blob/56739cdbdb7029fae5add307966c0b0612d3ea5a/POGOLib.Official/Net/RpcClient.cs#L517

Should this not be something like : 
var diff =(int)Math.Min((DateTime.Now - LastRpcRequest).TotalMilliseconds, int.MaxValue);
this calculates the difference in milliseconds between two times.
The original code takes the milliseconds of 2 times and calculates then the difference.
eg:
DateTime.Now = 2017/11/19 12:00:01.000
LastRpcRequest = 2017/11/19 12:00:00.200
in the original code diff= 0
and i think it should be 800

**Comment by Furtif** [comment]
Hello :-) if you have fix for it propose changes :-)

**Comment by Furtif** [comment]
@PeterDM65 look https://github.com/mtaheij/PoGo-UWP/pull/185
